CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM"
(date_time VARCHAR(32),
metric_id VARCHAR(64),
temperature NUMERIC);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS

INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM date_time, metric_id, temperature
FROM   "SOURCE_SQL_STREAM_001";